### ISSUE TITLE
[Bug] Jesus toggle command crashes the game

### ISSUE THREAD

**Issue by DoShhPlease** [MatHax/Client#10]
### Describe the bug

Jesus crashes the game. I simply typed .toggle jesus and my game crashed and if i load up in any server singleplayer or multiplayer it also just crashes. I had to use the main menu click gui button to disable jesus before joining back to fix this.

### Steps to reproduce

```bash
I was in a singleplayer world and I typed .toggle jesus then enter
```

### MatHax Legacy Version

1.6.4

### Minecraft Version

1.18

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Send the crash report/log.

**Comment by DoShhPlease** [comment]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 06/12/2021, 09:33
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_265.method_1096(double, double, double)" because "$$6" is null
	at net.minecraft.class_5329.method_29285(class_5329.java:109)
	at net.minecraft.class_5329.computeNext(class_5329.java:19)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:464)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:868)
	at net.minecraft.class_1297.method_20736(class_1297.java:943)
	at net.minecraft.class_1297.method_17835(class_1297.java:900)
	at net.minecraft.class_1297.method_5784(class_1297.java:633)
	at net.minecraft.class_1309.method_26318(class_1309.java:2247)
	at net.minecraft.class_1309.method_6091(class_1309.java:2192)
	at net.minecraft.class_1309.method_6007(class_1309.java:2643)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1472.method_6007(class_1472.java:139)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.method_18762(class_3218.java:696)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:357)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:325)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_5329.method_29285(class_5329.java:109)
	at net.minecraft.class_5329.computeNext(class_5329.java:19)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:464)
	at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:868)
	at net.minecraft.class_1297.method_20736(class_1297.java:943)
	at net.minecraft.class_1297.method_17835(class_1297.java:900)
	at net.minecraft.class_1297.method_5784(class_1297.java:633)
	at net.minecraft.class_1309.method_26318(class_1309.java:2247)
	at net.minecraft.class_1309.method_6091(class_1309.java:2192)
	at net.minecraft.class_1309.method_6007(class_1309.java:2643)
	at net.minecraft.class_1308.method_6007(class_1308.java:545)
	at net.minecraft.class_1296.method_6007(class_1296.java:127)
	at net.minecraft.class_1429.method_6007(class_1429.java:58)
	at net.minecraft.class_1472.method_6007(class_1472.java:139)
	at net.minecraft.class_1309.method_5773(class_1309.java:2349)
	at net.minecraft.class_1308.method_5773(class_1308.java:345)
	at net.minecraft.class_3218.method_18762(class_3218.java:696)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:357)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:325)

-- Entity being ticked --
Details:
	Entity Type: minecraft:sheep (net.minecraft.class_1472)
	Entity ID: 520
	Entity Name: Sheep
	Entity's Exact location: 61.83, 69.00, -556.82
	Entity's Block location: World: (61,69,-557), Section: (at 13,5,3 in 3,4,-35; chunk contains blocks 48,-64,-560 to 63,319,-545), Region: (0,-2; contains chunks 0,-64 to 31,-33, blocks 0,-64,-1024 to 511,319,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	at net.minecraft.class_3218.method_31420(class_3218.java:357)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:325)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['xsi'/75, l='ServerLevel[the newest version uwu]', x=92.60, y=64.00, z=-520.92]]
	Chunk stats: 3850
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,75,-128), Section: (at 0,11,0 in -4,4,-8; chunk contains blocks -64,-64,-128 to -49,319,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 453257 game time, 144602 day time
	Level name: the newest version uwu
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 12038 (now: true), thunder time: 37557 (now: false)
	Known server brands: vanilla, fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18
	Minecraft Version ID: 1.18
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1012135696 bytes (965 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 9
	Microarchitecture: Kaby Lake
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x1c81
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6647
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 24477.42
	Virtual memory used (MB): 11900.97
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		baritone: Baritone 1.18-SNAPSHOT
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.8
		java: OpenJDK 64-Bit Server VM 17
		mathaxlegacy: MatHax Legacy 1.6.4
		minecraft: Minecraft 1.18
	Server Running: true
	Player Count: 1 / 8; [class_3222['xsi'/75, l='ServerLevel[the newest version uwu]', x=92.60, y=64.00, z=-520.92]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

--- MatHax Legacy ---
Version: v1.6.4

[Movement]:
Jesus (jesus)
No Fall (no-fall)

[Render]:
Background (background)
HUD (hud)

[Player]:
Anti Hunger (anti-hunger)

[Chat]:
Stay Hydrated (stay-hydrated)

[Misc]:
Anti Packet Kick (anti-packet-kick)

[Client]:
Capes (capes)
Discord RPC (discord-rpc)
Middle Click Friend (middle-click-friend)

**Comment by Matejko06** [comment]
Can you give me a screenshot of Jesus settings you used?
