### ISSUE TITLE
[Bug] crashes 1.17.1

### ISSUE THREAD

**Issue by MIUNO** [MatHax/Client#114]
### Describe the bug

crash at a clean start

### Steps to reproduce

```bash
[23:25:06] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.13.3
[23:25:06] [main/INFO]: Loading 5 mods:
	- baritone 1.7.0 via mathax
	- fabricloader 0.13.3
	- java 16
	- mathax 1.7.4
	- minecraft 1.17.1
[23:25:06] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/miuno/AppData/Roaming/.tlauncher/legacy/Minecraft/files/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[23:25:06] [main/INFO]: Compatibility level set to JAVA_16
[23:25:07] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/world/SodiumChunkManager (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/world/SodiumChunkManager)
[23:25:07] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/util/collections/FixedLongHashTable)
[23:25:07] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.IllegalArgumentException
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:418) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.IllegalArgumentException
	at com.google.gson.internal.$Gson$Preconditions.checkArgument($Gson$Preconditions.java:46) ~[gson-2.8.0.jar:?]
	at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:532) ~[gson-2.8.0.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:120) ~[Fabric%201.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) ~[fabric-loader-0.13.3.jar:?]
	... 2 more
```

### MatHax Version

1.7.4

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [x] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Try reinstalling, i fixed this issue 2 days ago.
