### ISSUE TITLE
[Bug] [Crash] when I activated EXPTrower

### ISSUE THREAD

**Issue by NotMathew** [MatHax/Client#30]
### Describe the bug

08:11:44.407
[MatHax Legacy] Systems saved in 258 milliseconds.
08:11:45.428
Reported exception thrown!
net.minecraft.class_148: Ticking entity
	at net.minecraft.class_1937.method_18472(class_1937.java:494)
	at net.minecraft.class_638.method_32124(class_638.java:201)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:197)
	at net.minecraft.class_310.method_1574(class_310.java:1751)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalArgumentException: Invalid hand null
	at net.minecraft.class_1309.method_5998(class_1309.java:1900)
	at net.minecraft.class_636.method_2919(class_636.java:356)
	at mathax.legacy.client.systems.modules.player.EXPThrower.lambda$onTick$0(EXPThrower.java:26)
	at mathax.legacy.client.utils.player.Rotations$Rotation.runCallback(Rotations.java:224)
	at mathax.legacy.client.utils.player.Rotations$Rotation.sendPacket(Rotations.java:220)
	at mathax.legacy.client.utils.player.Rotations.onSendMovementPacketsPost(Rotations.java:125)
	at mathax.legacy.client.eventbus.listeners.LambdaListener.call(LambdaListener.java:79)
	at mathax.legacy.client.eventbus.EventBus.post(EventBus.java:47)
	at net.minecraft.class_746.handler$zdn000$onSendMovementPacketsTail(class_746.java:2399)
	at net.minecraft.class_746.method_3136(class_746.java:300)
	at net.minecraft.class_746.method_5773(class_746.java:225)
	at net.minecraft.class_638.method_18646(class_638.java:218)
	at net.minecraft.class_1937.method_18472(class_1937.java:487)
	... 14 more
08:11:45.441
[MatHax Legacy] Systems are saving...
08:11:46.411

AL lib: (EE) alc_cleanup: 1 device not closed
08:11:46.411
Process crashed with exit code -1

### Steps to reproduce

```bash
when i was activating EXPThrower, it suddenly crashed
```

### MatHax Legacy Version

1.6.6

### Minecraft Version

1.18.1 fabric-loader 0.12.12

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by Matejko06** [comment]
Does it still happen with latest version? v1.6.9

**Comment by mathe2006w** [comment]
v1.6.5 probably
