### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by forota123** [MatHax/Client#70]
### Describe the bug

Step crashes

### Steps to reproduce

```bash
I toggled step on. Here:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/24/22, 6:41 PM
Description: Ticking entity

java.lang.ClassCastException: class java.util.stream.ReferencePipeline$Head cannot be cast to class java.lang.Iterable (java.util.stream.ReferencePipeline$Head and java.lang.Iterable are in module java.base of loader 'bootstrap')
	at mathax.client.systems.modules.movement.Step.getCollisions(Step.java:139)
	at mathax.client.systems.modules.movement.Step.shouldStep(Step.java:135)
	at mathax.client.systems.modules.movement.Step.onPlayerMove(Step.java:97)
	at mathax.client.eventbus.listeners.LambdaListener.call(LambdaListener.java:73)
	at mathax.client.eventbus.EventBus.post(EventBus.java:44)
	at net.minecraft.class_1297.handler$zdj000$onMove(class_1297.java:4546)
	at net.minecraft.class_1297.method_5784(class_1297.java)
	at net.minecraft.class_746.method_5784(class_746.java:916)
	at net.minecraft.class_1309.method_26318(class_1309.java:2244)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_1657.method_6091(class_1657.java:1591)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1657.method_6007(class_1657.java:559)
	at net.minecraft.class_746.method_6007(class_746.java:832)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_746.method_5773(class_746.java:210)
	at net.minecraft.class_638.method_18646(class_638.java:179)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_638.method_32124(class_638.java:167)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:163)
	at net.minecraft.class_310.method_1574(class_310.java:1750)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mathax.client.systems.modules.movement.Step.getCollisions(Step.java:139)
	at mathax.client.systems.modules.movement.Step.shouldStep(Step.java:135)
	at mathax.client.systems.modules.movement.Step.onPlayerMove(Step.java:97)
	at mathax.client.eventbus.listeners.LambdaListener.call(LambdaListener.java:73)
	at mathax.client.eventbus.EventBus.post(EventBus.java:44)
	at net.minecraft.class_1297.handler$zdj000$onMove(class_1297.java:4546)
	at net.minecraft.class_1297.method_5784(class_1297.java)
	at net.minecraft.class_746.method_5784(class_746.java:916)
	at net.minecraft.class_1309.method_26318(class_1309.java:2244)
	at net.minecraft.class_1309.method_6091(class_1309.java:2189)
	at net.minecraft.class_1657.method_6091(class_1657.java:1591)
	at net.minecraft.class_1309.method_6007(class_1309.java:2640)
	at net.minecraft.class_1657.method_6007(class_1657.java:559)
	at net.minecraft.class_746.method_6007(class_746.java:832)
	at net.minecraft.class_1309.method_5773(class_1309.java:2346)
	at net.minecraft.class_1657.method_5773(class_1657.java:274)
	at net.minecraft.class_746.method_5773(class_746.java:210)
	at net.minecraft.class_638.method_18646(class_638.java:179)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 1976758
	Entity Name: Duhano
	Entity's Exact location: 0.50, 120.00, 0.50
	Entity's Block location: World: (0,120,0), Section: (at 0,8,0 in 0,7,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_638.method_32124(class_638.java:167)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:163)

-- Affected level --
Details:
	All players: 1 total; [class_746['Duhano'/1976758, l='ClientLevel', x=0.50, y=120.00, z=0.50]]
	Chunk stats: 256, 81
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,120,0), Section: (at 0,8,0 in 0,7,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 166798 game time, 1000 day time
	Server brand: Purpur
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, DuPack 0.3 beta

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft

```

### MatHax Version

1.7.1

### Minecraft Version

1.17.1

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported.
(I have checked every bug report on github)

- [X] This is a valid bug.
(I am able to reproduce this on the latest dev build)

**Comment by white-devil42** [comment]
are you using any other mods?
